module.exports.dataDonThuoc = {
  hospital: {
    avatar:
      "https://printgo.vn/uploads/file-logo/1/x512x512.747d5219a89da42fe2408c84760b2bf3.ai.1.png.pagespeed.ic.onO18wiIuj.webp",
    name: "Bệnh viện Bạch Mai",
    phone: "024(6) 484 875",
    address: "35 Lê Văn Thiêm, P.Thanh Xuân Trung, Q.Thanh Xuân, Hà Nội",
  },
  bac_si: {
    ho_ten: "Nguyen Van B",
  },
  time: "9 : 00",
  date: "Ngày 1 tháng 1 năm 2022",
  sinh_hieu:
    "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus, cumque.",
  benh_nhan: {
    ma_dinh_danh: "0231244446",
    ho_ten: "Nguyễn Văn Đn",
    gioi_tinh: "Nam",
    tuoi: 20,
    so_dien_thoai: "0933221233",
    dia_chi: "Số 35 Lê Văn Thiêm",
    nguoi_lien_he: "Nguyễn Văn B",
  },
  chuan_doan_benh_chinh: [
    { id: 1, ten_benh: "Bệnh án gì dài vl" },
    { id: 2, ten_benh: "Bệnh án gì dài vl" },
  ],
  chuan_doan_benh_phu: [
    { id: 1, ten_benh: "Bệnh án gì dài vl" },
    { id: 2, ten_benh: "Bệnh án gì dài vl" },
    { id: 3, ten_benh: "Bệnh án gì dài vl" },
  ],
  thuoc: [
    {
      so_dangky: "#2311",
      ten_thuoc:
        "New Ameflu Multis Multisymptoeflu Multis Multisymptoeflu Multis Multisymptoeflu Multis Multisymptoeflu Multis Multisymptom Mult",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 ,  Tối: 1 Tối: 1",
      chi_dan:
        "New Ameflu Multisymptom Relief New Ameflu Multisymptom ReliefReliefReliefReliefRelief",
    },
    {
      so_dangky: "#2311",
      ten_thuoc: "New Ameflu Multis Multisymptom Mult",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 ,  Tối: 1 Tối: 1",
      chi_dan:
        "New Ameflu Multisymptom Relief New Ameflu Multisymptom ReliefReliefReliefReliefRelief",
    },
    {
      so_dangky: "#2311",
      ten_thuoc: "New Ameflu Multisymptom Relief",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 , Tối: 1",
      chi_dan: "New Ameflu Multisymptom Relief New Ameflu Multisymptom Relief",
    },
    {
      so_dangky: "#2311",
      ten_thuoc: "New Ameflu Multisymptom Relief",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 , Tối: 1",
      chi_dan: "New Ameflu Multisymptom Relief New Ameflu Multisymptom Relief",
    },
    {
      so_dangky: "#2311",
      ten_thuoc: "New Ameflu Multisymptom Relief",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 , Tối: 1",
      chi_dan: "New Ameflu Multisymptom Relief New Ameflu Multisymptom Relief",
    },
    {
      so_dangky: "#2311",
      ten_thuoc: "New Ameflu Multisymptom Relief",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 , Tối: 1",
      chi_dan: "New Ameflu Multisymptom Relief New Ameflu Multisymptom Relief",
    },
    {
      so_dangky: "#2311",
      ten_thuoc: "New Ameflu Multisymptom Relief",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 , Tối: 1",
      chi_dan: "New Ameflu Multisymptom Relief New Ameflu Multisymptom Relief",
    },
    {
      so_dangky: "#2311",
      ten_thuoc: "New Ameflu Multisymptom Relief",
      so_luong: "20 viên",
      thoi_gian_bat_dau: "02/12/2021",
      thoi_gian_ket_thuc: "02/12/2021",
      cach_dung: "Uống",
      lieu_dung: "Sáng 1 , Tối: 1",
      chi_dan: "New Ameflu Multisymptom Relief New Ameflu Multisymptom Relief",
    },
  ],
  loi_dan:
    "Esse laborum culpa velit nostrud ea magna aliquip irure labore laborum sit nisi voluptate. Minim commodo ullamco do officia culpa reprehenderit irure do ad culpa duis. Minim commodo ullamco do officia culpa reprehenderit irure do ad culpa duis.",
  ngay_tai_kham: "",
};
module.exports.dataPhieuTiepDon = {
  hospital: {
    avatar:
      "https://printgo.vn/uploads/file-logo/1/x512x512.747d5219a89da42fe2408c84760b2bf3.ai.1.png.pagespeed.ic.onO18wiIuj.webp",
    name: "Bệnh viên Đa khoa HNsdaa dasdsa dsadasd sadasdsa ádasdas",
    phone: "024(6) 484 875",
    address: "35 Lê Văn Thiêm, P.Thanh Xuân Trung, Q.Thanh Xuân, Hà Nội",
  },
  nhan_vien: {
    benh_vien: "PHÒNG KHÁM PHỤ KHOA - THÁI THỊNH",
    dia_chi: " Phường Đức Giang, Q.Long Biên, TP.Hà Nội",
    ma_dinh_danh: "0231244446",
    ho_ten: "Nguyễn Văn A",
    gioi_tinh: "Nữ",
    nam_sinh: 1992,
    so_the_BHYT: "GD-928-4902500614",
    han_the: "01/01/2025",
    doi_tuong: "Bảo hiểm -80%",
    kham_ngay: " 07:51 - 13/01/2022",
  },
};
